export default function Head() {
  return (
    <>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <title>GMA Internal Dashboard</title>
      <meta name="description" content="Generated by create next app" />
    </>
  );
}
